server.port=9090
spring.application.name=stats-server

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/stats-db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:stats}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:stats}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

management.endpoints.web.exposure.include=health,info
