server.port=8080
spring.application.name=explore-with-me

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/ewm
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:ewm}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:ewm}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

# SQL init
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

# Stats
stats.server.url=http://stats-server:9090
logging.level.root=DEBUG
# Jackson
spring.jackson.serialization.write-dates-as-timestamps=false

